### ISSUE TITLE
バイナリーデータの扱いについて

### ISSUE THREAD

**Issue by MasanoriKono** [fujitake/vantiq-related#88]
V1.34がリリースされたら以下を[Vantiq アプリ開発 逆引きリファレンス](https://github.com/fujitake/vantiq-related/blob/main/vantiq-apps-development/docs/jp/reverse-lookup.md)記載する。タイトルは検討する。

### バイナリデータを処理したい (V1.34以降)
Vantiqは バイナリーデータの入力はできません。
Base64等でエンコードした文字列を受けることはできます。また制限がありますが、文字列からbyte配列を抽出し、処理を行うことができます。

```vail
procedure printBase64( encodedValue String )
// encodedValue is base64 encoded like "AXXXXXXXXXXXXXXXXXXw=="

var decodedValue = Decode.base64Raw(encodedValue)
var bytes = decodedValue.getBytes()

for (i in range(0, bytes.length())) {
    log.info("Byte value {}:{}", [i, bytes[i].intValue()])
}
```

**Comment by fujitake** [comment]
@MasanoriKono 
この件、なぜv1.34以降で記載することになるんでしょう？
今v1.33でも Decode.base64, Encode.base64 ってありますよ。
https://dev.vantiq.co.jp/docs/system/rules/index.html#encoding-decoding-and-hashing

あと、タイトル(件名)と内容が違いすぎるかと思います。バイナリデータは処理できないので、バイナリデータを処理したい、として、バイナリデータの入力はできません、と記載するのは、どうかと。。
Base64のエンコード、デコードを行いたい
とかにしませんか？

**Comment by MasanoriKono** [comment]
ありがとうございます。
あとバイナリデータの扱いとする場合、Documentへアップロードも言及しておくべきかと思いました。
